---
- hosts: all
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  tasks:
  - name: Update cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400
    become: yes

  - name: Aptitude safe-upgrade
    apt: upgrade=safe
    become: yes

  - name: Install system packages
    become: yes
    package:
      name={{ item }}
      state=present
    with_items:
      - libccid
      - scdaemon
      - gnupg2

  - name: Copy nitrokey rules
    become: yes
    copy:
        src: "41-nitrokey.rules"
        dest: "/etc/udev/rules.d/41-nitrokey.rules"
        owner: root
        group: root
        mode: 0644

  - name: patch libccid config
    become: yes
    patch:
        src: "libccid_Info.plist.diff"
        dest: "/etc/libccid_Info.plist"
    when: ansible_distribution_release == "trusty"
